name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install python 3
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Runs unmock tests
      # - name: Run unmock tests server side
      #   run: python3 test_unmock.py

      # Runs mock tests
      # - name: Run mock tests server side
      #   run: python3 test_mock_apis.py

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          STRIPE_SECRET_KEY: ${{secrets.SRIPE_SECRET_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
      - run: npx eslint src/
